#=
Highly divisible triangular number

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
=#
include("Problem 003.jl")

function countFactors(n)
    primeFactor = factor(n)
    e = primeFactor["e"]
    reduce(*, e .+ 1) # Combinatorics - possible combinations of primes (include 0 exponent)
end

function findTriangle(d::Integer)
    index = 2
    ∑ = 3
    while countFactors(∑) < d
        index += 1
        ∑ = sum(1:index)
    end
    ∑
end

findTriangle(500)
# 76576500
