#=
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
=#

# Sequence is Odd, Even, Odd, Odd, Even, Odd, Odd, Even, ...

function ϕ(limit, ϕ_0, ϕ_1, evens = 0)
  if ϕ_0 <= limit
    if ϕ_0 % 2 == 0
      evens += ϕ_0
    end
    ϕ(limit, ϕ_0 + ϕ_1, ϕ_0, evens)
  else
    evens
  end
end

ϕ(4 * 10 ^ 6, 2, 1)
# 4613732
